package Entities;
// Generated Jun 27, 2016 2:25:48 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags {

    private int id;
    private String Email_User;
    private String tagName;
    private String description;
    private boolean status;

    public Tags() {
    }

    public Tags(int id, String Email_User, String tagName, String description, boolean status) {
        this.id = id;
        this.Email_User = Email_User;
        this.tagName = tagName;
        this.description = description;
        this.status = status;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEndUser() {
        return this.Email_User;
    }

    public void setEndUser(String Email_User) {
        this.Email_User = Email_User;
    }

    public String getTagName() {
        return this.tagName;
    }

    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }
}
